(in-package :cl-user)
(defpackage cl-clblas
  (:use :cl)
  (:export ;; enums
           :clblasOrder
           :clblasTranspose
           :clblasUplo
           :clblasDiag
           :clblasSide
           :clblasStatus

           ;; functions
           :clblasGetVersion
           :clblasSetup
           :clblasTeardown
           :clblasSswap
           :clblasDswap
           :clblasCswap
           :clblasZswap
           :clblasSscal
           :clblasDscal
           :clblasCscal
           :clblasZscal
           :clblasCsscal
           :clblasZdscal
           :clblasScopy
           :clblasDcopy
           :clblasCcopy
           :clblasZcopy
           :clblasSaxpy
           :clblasDaxpy
           :clblasCaxpy
           :clblasZaxpy
           :clblasSdot
           :clblasDdot
           :clblasCdotu
           :clblasZdotu
           :clblasCdotc
           :clblasZdotc
           :clblasSrotg
           :clblasDrotg
           :clblasCrotg
           :clblasZrotg
           :clblasSrotmg
           :clblasDrotmg
           :clblasSrot
           :clblasDrot
           :clblasCsrot
           :clblasZdrot
           :clblasSrotm
           :clblasDrotm
           :clblasSnrm2
           :clblasDnrm2
           :clblasScnrm2
           :clblasDznrm2
           :clblasiSamax
           :clblasiDamax
           :clblasiCamax
           :clblasiZamax
           :clblasSasum
           :clblasDasum
           :clblasScasum
           :clblasDzasum
           :clblasSgemv
           :clblasDgemv
           :clblasCgemv
           :clblasZgemv
           :clblasSsymv
           :clblasDsymv
           :clblasChemv
           :clblasZhemv
           :clblasStrmv
           :clblasDtrmv
           :clblasCtrmv
           :clblasZtrmv
           :clblasStrsv
           :clblasDtrsv
           :clblasCtrsv
           :clblasZtrsv
           :clblasSger
           :clblasDger
           :clblasCgeru
           :clblasZgeru
           :clblasCgerc
           :clblasZgerc
           :clblasSsyr
           :clblasDsyr
           :clblasCher
           :clblasZher
           :clblasSsyr2
           :clblasDsyr2
           :clblasCher2
           :clblasZher2
           :clblasStpmv
           :clblasDtpmv
           :clblasCtpmv
           :clblasZtpmv
           :clblasStpsv
           :clblasDtpsv
           :clblasCtpsv
           :clblasZtpsv
           :clblasSspmv
           :clblasDspmv
           :clblasChpmv
           :clblasZhpmv
           :clblasSspr
           :clblasDspr
           :clblasChpr
           :clblasZhpr
           :clblasSspr2
           :clblasDspr2
           :clblasChpr2
           :clblasZhpr2
           :clblasSgbmv
           :clblasDgbmv
           :clblasCgbmv
           :clblasZgbmv
           :clblasStbmv
           :clblasDtbmv
           :clblasCtbmv
           :clblasZtbmv
           :clblasSsbmv
           :clblasDsbmv
           :clblasChbmv
           :clblasZhbmv
           :clblasStbsv
           :clblasDtbsv
           :clblasCtbsv
           :clblasZtbsv
           :clblasSgemm
           :clblasDgemm
           :clblasCgemm
           :clblasZgemm
           :clblasStrmm
           :clblasDtrmm
           :clblasCtrmm
           :clblasZtrmm
           :clblasStrsm
           :clblasDtrsm
           :clblasCtrsm
           :clblasZtrsm
           :clblasSsyrk
           :clblasDsyrk
           :clblasCsyrk
           :clblasZsyrk
           :clblasSsyr2k
           :clblasDsyr2k
           :clblasCsyr2k
           :clblasZsyr2k
           :clblasSsymm
           :clblasDsymm
           :clblasCsymm
           :clblasZsymm
           :clblasChemm
           :clblasZhemm
           :clblasCherk
           :clblasZherk
           :clblasCher2k
           :clblasZher2k
           :clblasMatrixSizeInfo
           :clblasCreateMatrix
           :clblasCreateMatrixWithLd
           :clblasCreateMatrixFromHost
           :clblasWriteSubMatrix
           :clblasWriteSubMatrixAsync
           :clblasReadSubMatrix
           :clblasReadSubMatrixAsync
           :clblasCopySubMatrix
           :clblasCopySubMatrixAsync
           :clblasWriteVector
           :clblasWriteVectorAsync
           :clblasReadVector
           :clblasReadVectorAsync
           :clblasCopyVector
           :clblasCopyVectorAsync
           :clblasWriteMatrix
           :clblasWriteMatrixAsync
           :clblasReadMatrix
           :clblasReadMatrixAsync
           :clblasCopyMatrix
           :clblasCopyMatrixAsync
           :clblasFillVector
           :clblasFillVectorAsync
           :clblasFillMatrix
           :clblasFillSubMatrix
           :clblasFillSubMatrixAsync))
